name = "Majoranas"
uuid = "c0bcf24a-0299-47db-9920-c7627388ccab"
authors = ["William Samuelson <william.samuelson@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
