name = "Majoranas"
uuid = "c0bcf24a-0299-47db-9920-c7627388ccab"
authors = ["William Samuelson <william.samuelson@gmail.com> and contributors"]
version = "1.3.0"

[deps]
AffineRayleighOptimization = "afc0e0ae-cd0a-41ee-b0f5-7950de095d62"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
QuantumDots = "312194fd-fec5-4b07-ba1c-a40d7013a56a"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[sources.AffineRayleighOptimization]
url = "https://github.com/williamesamuelson/AffineRayleighOptimization.jl"

[sources.QuantumDots]
url = "https://github.com/cvsvensson/QuantumDots.jl"

[compat]
AffineRayleighOptimization = "2"
LinearSolve = "2"
Combinatorics = "1"
OrderedCollections = "1.6.3"
QuantumDots = "0.15"
julia = "1.10"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Test", "TestItemRunner", "Random"]
